# --- Appearance ---
background_opacity 0.7
window_padding_width 15
confirm_os_window_close 0

# --- Dynamic Theming ---
# This pulls the colors Noctalia generates from your wallpaper
#include ~/.cache/noctalia/kitty.conf

include /home/subhro/.cache/wallust/colors-kitty.conf
