-- Generated by manual translation (RIP hyprconf2lua)

---@module 'hl'

hl.config({
    animations = {
        enabled = true,
        
        -- The Math (Bézier Curves)
        bezier = {
            "wind, 0.05, 0.9, 0.1, 1.05",
            "winIn, 0.1, 1.1, 0.1, 1.1",
            "winOut, 0.3, -0.3, 0, 1",
            "liner, 1, 1, 1, 1",
        },
        
        -- The Execution
        animation = {
            "windows, 1, 6, wind, slide",
            "windowsIn, 1, 6, winIn, slide",
            "windowsOut, 1, 5, winOut, slide",
            "windowsMove, 1, 5, wind, slide",
            "border, 1, 1, liner",
            "fade, 1, 10, default",
            "workspaces, 1, 5, wind",
        },
    },
})

hl.config({
    decoration = {
        rounding = 10,
        blur = {
            enabled = true,
            size = 5,
            passes = 3,
            new_optimizations = true,
        },
    },
})