# ==========================================
# SUPERVISOR & HARDWARE
# ==========================================
monitor=,preferred,auto,1.25

env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,20
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = COLOR_SCHEME,prefer-dark

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
}

xwayland {
  force_zero_scaling = true
}

#gestures {
#    workspace_swipe = true 
#}

# ==========================================
# THE UI SHELL (NOCTALIA)
# ==========================================
exec-once = qs -c noctalia-shell
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = hyprctl setcursor Bibata-Modern-Ice 20
# Start the Audio Engine
#exec-once = /usr/bin/pipewire
#exec-once = /usr/bin/wireplumber
#exec-once = /usr/bin/pipewire-pulse

# ==========================================
# THE BRAIN (MODULAR SOURCING)
# ==========================================
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/theme.conf
