-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ==========================================

-- SUPERVISOR & HARDWARE

-- ==========================================

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1.25,
})

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("GBM_BACKEND", "nvidia-drm")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.env("NVD_BACKEND", "direct")

hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")

hl.env("XCURSOR_SIZE", 20)

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("COLOR_SCHEME", "prefer-dark")

hl.config({
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

--gestures {

--    workspace_swipe = true 

--}

-- ==========================================

-- THE UI SHELL (NOCTALIA)

-- ==========================================


--exec-once = /usr/lib/polkit-kde-authentication-agent-1


-- Start the Audio Engine

--exec-once = /usr/bin/pipewire

--exec-once = /usr/bin/wireplumber

--exec-once = /usr/bin/pipewire-pulse

-- ==========================================

-- THE BRAIN (MODULAR SOURCING)

-- ==========================================

require("animations")
require("windowrules")
require("keybinds")
require("theme")

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("noctalia-shell")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 20")
end)
