-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Generated by nwg-displays on 2026-05-04 at 15:39:07. Do not edit manually.

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@165.0",
    position = "0x0",
    scale    = 1.25,
})
