# 1. Define Defaults FIRST (Standard '=' instead of '?=')
$color1 = rgba(cba6f7ff)
$color2 = rgba(89b4faff)

# 2. Source the cache (This will overwrite the defaults if it has data)
source = /home/subhro/.cache/wallust/colors-hyprland.conf

general {
    gaps_in = 6
    gaps_out = 14
    border_size = 2
    
    # Use the variables (Hyprland will now always have a value for these)
    col.active_border = $color1 $color2 45deg
    col.inactive_border = rgba(31324444)

    layout = dwindle
}

decoration {
    rounding = 14
    blur {
        enabled = true
        size = 6
        passes = 3
    }
    shadow {
        enabled = true
        range = 30
        color = rgba(00000099)
    }
}

animations {
    bezier = liner, 1, 1, 1, 1
    animation = borderangle, 1, 30, liner, loop
}
