-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- 1. Define Defaults FIRST (Standard '=' instead of '?=')

local color1 = "rgba(cba6f7ff)"

local color2 = "rgba(89b4faff)"

-- 2. Source the cache (This will overwrite the defaults if it has data)


hl.config({
    general = {
        gaps_in = 6,
        gaps_out = 14,
        border_size = 2,
        -- Use the variables (Hyprland will now always have a value for these)
        layout = "dwindle",
        col = {
            active_border = { colors = { "rgba(cba6f7ff)", "rgba(89b4faff)" }, angle = 45 },
            inactive_border = "rgba(31324444)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 14,
        blur = {
            enabled = true,
            size = 6,
            passes = 3,
        },
        shadow = {
            enabled = true,
            range = 30,
            color = "rgba(00000099)",
        },
    },
})

hl.config({
    animations = {
    },
})
