-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Wayland/XWayland Bug Fixes

hl.window_rule({
    name  = "suppress-maximize",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland",
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        float = 1,
        fullscreen = 0,
        pin = 0,
    },
    no_focus = 1,
})

-- Smart Floating & Opacity

hl.window_rule({
    name  = "float-pavucontrol",
    match = {
        class = "^(pavucontrol)$",
    },
    float = 1,
})

hl.window_rule({
    name  = "float-polkit",
    match = {
        class = "^(polkit-kde-authentication-agent-1)$",
    },
    float = 1,
    center = 1,
})

hl.window_rule({
    name  = "terminal-opacity",
    match = {
        class = "^(kitty)$",
    },
    opacity = "0.90, 0.90",
})

-- Hardware Acceleration & Latency Bypass (CS2 & Steam)

hl.window_rule({
    name  = "tear-cs2",
    match = {
        class = "^(cs2)$",
    },
    immediate = 1,
})

hl.window_rule({
    name  = "tear-steam-1",
    match = {
        class = "^(steam_app_270880)$",
    },
    immediate = 1,
})

hl.window_rule({
    name  = "tear-steam-2",
    match = {
        class = "^(steam_app_227300)$",
    },
    immediate = 1,
})
