# Wayland/XWayland Bug Fixes
windowrule {
    name = suppress-maximize
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland
    match:class = ^$
    match:title = ^$
    match:xwayland = 1
    match:float = 1
    match:fullscreen = 0
    match:pin = 0
    no_focus = 1
}

# Smart Floating & Opacity
windowrule {
    name = float-pavucontrol
    match:class = ^(pavucontrol)$
    float = 1
}

windowrule {
    name = float-polkit
    match:class = ^(polkit-kde-authentication-agent-1)$
    float = 1
    center = 1
}

windowrule {
    name = terminal-opacity
    match:class = ^(kitty)$
    opacity = 0.90 0.90
}

# Hardware Acceleration & Latency Bypass (CS2 & Steam)
windowrule {
    name = tear-cs2
    match:class = ^(cs2)$
    immediate = 1
}

windowrule {
    name = tear-steam-1
    match:class = ^(steam_app_270880)$
    immediate = 1
}

windowrule {
    name = tear-steam-2
    match:class = ^(steam_app_227300)$
    immediate = 1
}
